platform: &platform
    platform: iosl

device_config: &device_config
    ios:
        platformName: 'ios'
        platformVersion: '16.1'
        deviceName: 'iPhone 14 Pro'
        automationName: 'XCUITest'
        appPackage: ''
        appActivity: ''
        noReset: 'True'
        folder: '/Users/jkee/Desktop/extraStaging.app'
    android:
        platformName: 'android'
        platformVersion: '9'
        deviceName: 'Pixel'
        automationName: 'uiautomator2'
        appPackage: 'org.wordpress.android'
        appActivity: 'org.wordpress.android.ui.WPLaunchActivity'
        noReset: 'True'
        folder: '/Users/jkee/Desktop/extraStaging.app'

production:
    <<: *platform
    <<: *device_config
